### ISSUE TITLE
Enhancement: show subordinate places

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#19]
![Screenshot (14)_LI](https://user-images.githubusercontent.com/6324175/88118297-880c8200-cbbd-11ea-8af7-a03d785f99d7.jpg)

When you present a shared place, this module shows already the shared place hierarchy (1). My suggestion is to show also all shared places **one hierarchy level below** this shared place (2) as a table. This would allow us to navigate in both directions of the hierarchy.

Two questions regarding the summary:
- is "Breisgau-Hochschwarzwald, Baden-Württemberg, DEU" correct or should it be only "Breisgau-Hochschwarzwald"? Is this redundant to the above line "shared place hierarchy"?
- is there a "shared place icon" missing in the GOV hierarchy line? That there are no icons in front of "Regierungsbezirk Freiburg" und "Europäische Union" is ok, because these two are no shared places in my database.

**Comment by ric2016** [comment]
Note that you can alreaddy use the Vesta place hierarchy (restricted to shared places) to get a list of child places of a shared place. It may be indeed useful to show these directly for the shared place as well.

Regarding the summary, this doesn't look right - It is supposed to always show the first part of the name, I'll have to look into this.

**Comment by hartenthaler** [comment]
regarding "summary - only show first part of the name": maybe this is a leftover, because I used this full form with "," before. I used your migration tool for some of my shared places, but I also changed the name manually for some other entries. Maybe I have to edit a table in the database? Which one?

**Comment by ric2016** [comment]
> Maybe I have to edit a table in the database?

That shouldn't be necessary.

Regardless of how the shared place names have been adjusted (via data fix/ manually): Do you now have only shared places left with 'simple' names (names without comma-separated hierarchy)? Otherwise you should get a note in the shared places list indicating potential problems.

Can you use the (Vesta) clippings cart to clip the respective shared places, and attach them here (or send them to me via email)? It may be easier to debug that way.

**Comment by hartenthaler** [comment]
All my 52 shared places are now "simple". Here are some of them:
[clippings (2).zip](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/4960718/clippings.2.zip)

I found the possibility to restrict the place hierarchy to shared places only. Nice feature! Thank you!

I just generated a new shared place (Urfahr) and this is shown as all the others in the first line of the summary with full hierarchy.

![Screenshot (20)_LI](https://user-images.githubusercontent.com/6324175/88194753-77045500-cc3f-11ea-8a1b-aecf91c54638.jpg)

There is a shared place icon missing (before Linz as "Stadtbezirk"), but in this case, this is ok, because "Linz (Stadtbezirk)" is not an shared place for me. In this case, the modeling of Linz in GOV is wrong, I will change this (at the moment it is in GOV: Linz (Stadt), Linz (Kreisfreie Stadt), Linz (Stadtbezirk)).

Why is the used language slo instead of deu for Österreich?

**Comment by ric2016** [comment]
> Why is the used language slo instead of deu for Österreich?

See linked issue for this.

**Comment by ric2016** [comment]
Added in latest release:
1. List of lower-level shared places, as suggested (in addition to the place hierarchy list module).
2. Fixed missing icon in first element of GOV hierarchy.

Regarding the other questions:
The summary actually displays the place with full hierarchy by design. I have added a helptext to clarify this, also so that I won't get confused myself again ;-)
This indeed means that 'Shared place hierarchy' is usually redundant. I have removed it for now.
